# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
