# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20170216_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterecommendation',
            name='website_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
