# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_websiterecommendation_website_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterecommendation',
            name='downvote',
            field=models.ManyToManyField(related_name='website_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websiterecommendation',
            name='upvote',
            field=models.ManyToManyField(related_name='website_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
