# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_bookrecommendation_recommended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.SubCategory'),
            preserve_default=False,
        ),
    ]
