# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170422_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='book_description',
            field=models.CharField(max_length=10000),
        ),
    ]
