# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170422_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='book_url',
            field=models.URLField(max_length=2000),
        ),
    ]
