# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_bookrecommendation_book_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrecommendation',
            unique_together=set([('category', 'subcategory', 'isbn')]),
        ),
    ]
