# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0021_bookrecommendation_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='bookmark',
            field=models.ManyToManyField(related_name='book_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='downvote',
            field=models.ManyToManyField(related_name='book_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrecommendation',
            name='upvote',
            field=models.ManyToManyField(related_name='book_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
