# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_videorecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecommendation',
            name='video_publish_date',
            field=models.DateTimeField(),
        ),
    ]
