# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20170508_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecommendation',
            name='video_id',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='videorecommendation',
            unique_together=set([('category', 'subcategory', 'video_id')]),
        ),
    ]
