# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0026_auto_20170508_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecommendation',
            name='bookmark',
            field=models.ManyToManyField(related_name='video_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videorecommendation',
            name='downvote',
            field=models.ManyToManyField(related_name='video_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videorecommendation',
            name='upvote',
            field=models.ManyToManyField(related_name='video_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
