# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterecommendation',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
