# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_websiterecommendation_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
