# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20180122_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
