# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_subcategory_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_img',
            field=models.ImageField(blank=True, upload_to='subcategory_images'),
        ),
    ]
