# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20180227_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_img',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images'),
        ),
    ]
